packages:
  - apps/*
  - packages/*
  - sdk/*

confirmModulesPurge: false
storeDir: .pnpm-store

catalog:
  '@logtape/logtape': ^2.0.2
  '@types/bun': ^1.3.9
  drizzle-orm: 1.0.0-beta.15-9485290
  typescript: ^5.9.3
  zod: ^4.3.6

onlyBuiltDependencies:
  - '-'
  - /
  - '@'
  - a
  - c
  - e
  - esbuild
  - g
  - i
  - l
  - msgpackr-extract
  - msw
  - inngest-cli
  - p
  - r
  - s
  - t
